config/routes.rb
Rails.application.routes.draw do

  root 'reports#report2'
  get 'stocks/index',to:'stocks#index'

  resources :stocks

  get 'reports/report1',to: 'reports#report1', as: 'report1'
  get 'reports/report2',to: 'reports#report2', as: 'report2'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord

  def self.unique_filtered_items

    @stock46 = (Stock.where("item_code LIKE ?", "4" + "%").or(Stock.where("item_code LIKE ?", "6" + "%")))
                .and(Stock.where("stock != ?", 0).or(Stock.where("qty_delivery != ?", 0)))
                .group(:item_code)

  end

  def self.sum_of_stocks

    total_stock_list = []
    others_stock_list = []
    warehouses_list = []
    warehouse_stock_list = []
    delivered_qty_list = []

    # I want to calculate the total stock of a single item = stock of the item where warehouse is 1,PROD,19,20,Others except 2
    # Others is sum of all instances except Total & 2
    # To calculate the total of each unique item, I need to store an array

    stock46_all_entries = Stock.where("item_code LIKE ?", "4" + "%").or(Stock.where("item_code LIKE ?", "6" + "%"))

    unique_filtered_items.each do |unq_item_entry|
      others_sum = 0.0
      total_sum = 0.0
      warehouses = []
      warehouse_stock = []
      qty_to_be_delivered = 0.0

      stock46_all_entries.each do |item_entry|

        if unq_item_entry.item_code == item_entry.item_code

          if item_entry.warehouse != "1" && item_entry.warehouse != "PROD" && item_entry.warehouse != "19" && item_entry.warehouse != "20" && item_entry.warehouse != "2"
            others_sum += item_entry.stock
          end

          if item_entry.warehouse != "2"
            total_sum += item_entry.stock
          end

          if item_entry.stock != 0
            if item_entry.warehouse == "1"
              warehouses.push("1")
              warehouse_stock.push(item_entry.stock)
            elsif item_entry.warehouse == "PROD"
              warehouses.push("PROD")
              warehouse_stock.push(item_entry.stock)
            elsif item_entry.warehouse == "19"
              warehouses.push("19")
              warehouse_stock.push(item_entry.stock)
            elsif item_entry.warehouse == "20"
              warehouses.push("20")
              warehouse_stock.push(item_entry.stock)
            elsif item_entry.warehouse == "2"
              warehouses.push("2")
              warehouse_stock.push(item_entry.stock)
            end
          end

          qty_to_be_delivered += item_entry.qty_delivery
        end
      end
      others_stock_list.push(others_sum)
      total_stock_list.push(total_sum)
      warehouses_list.push(warehouses)
      warehouse_stock_list.push(warehouse_stock)
      delivered_qty_list.push(qty_to_be_delivered)
    end

    return others_stock_list, total_stock_list, warehouses_list, warehouse_stock_list, delivered_qty_list
  end

  def self.filter_based_on_stock
    @nonempty_stock = Stock.where("stock > ?", 0.9)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def report1
    @stocks = Stock.filter_based_on_stock
  end

  def report2
    @stocks = Stock.unique_filtered_items
    @other_list, @total_list, @warehouses_list, @warehouse_stock_list, @quantity_to_be_delivered = Stock.sum_of_stocks
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:warehouse, :item_code, :description, :assortment, :item_group, :item_unit, :stock, :qty_delivery)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    if request.path == test_path
      return 'item active'
    else
      return 'item'
    end

  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Papa1</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'stocks/header' %>
    <%= yield %>
  </body>
</html>

app/views/reports/report1.html.erb
<p id="notice"><%= notice %></p>

<div class="table-responsive">
    <table class="tableFixHead table table-dark table-striped table-bordered table-sm">
      <thead>
      <tr>
        <th>Warehouse</th>
        <th>Item code</th>
        <th>Description</th>
        <th>Assortment</th>
        <th>Item group</th>
        <th>Item unit</th>
        <th>Stock</th>
        <th>Quantity to be delivered</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @stocks.each do |stock| %>
        <tr>
          <td><%= stock.warehouse %></td>
          <td><%= stock.item_code %></td>
          <td><%= stock.description %></td>
          <td><%= stock.assortment %></td>
          <td><%= stock.item_group %></td>
          <td><%= stock.item_unit %></td>
          <td><%= stock.stock %></td>
          <td><%= stock.qty_delivery %></td>
          <td><%= link_to 'Show', stock %></td>
          <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
          <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
</div>
</div>
<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/reports/report2.html.erb
<p id="notice"><%= notice %></p>

<div class="ui grid">
  <div class="centered fifteen wide column">
    <table class="BlackTableFixHead ui tablet stackable striped inverted table">
      <thead>
      <tr>
        <th>No.</th>
        <th>Item code</th>
        <th>Description</th>
        <th>Item unit</th>
        <th>Subhan Stock(1)</th>
        <th>Production Stock(PROD)</th>
        <th>Damaged Stock(19)</th>
        <th>Expired Stock(20)</th>
        <th>Others Stock</th>
        <th>Total Stock</th>
        <th>Quantity to be delivered</th>
        <th>Showroom Stock(2)</th>
      </tr>
      </thead>

      <tbody>
      <%item_idx = 0 %>

      <% @stocks.each do |stock| %>
        <tr>
          <td><%= item_idx+1 %>.</td>
          <td><%= stock.item_code %></td>
          <td><%= stock.description %></td>
          <td><%= stock.item_unit %></td>

          <% if @warehouses_list[item_idx].include?("1") %>
            <% warehouse_idx = @warehouses_list[item_idx].index("1") %>
            <td><%= @warehouse_stock_list[item_idx][warehouse_idx] %></td>
          <% else %><td> - </td>
          <% end %>

          <% if @warehouses_list[item_idx].include?("PROD") %>
            <% warehouse_idx = @warehouses_list[item_idx].index("PROD") %>
            <td><%= @warehouse_stock_list[item_idx][warehouse_idx] %></td>
          <% else %><td> - </td>
          <% end %>

          <% if @warehouses_list[item_idx].include?("19") %>
            <% warehouse_idx = @warehouses_list[item_idx].index("19") %>
            <td><%= @warehouse_stock_list[item_idx][warehouse_idx] %></td>
          <% else %><td> - </td>
          <% end %>

          <% if @warehouses_list[item_idx].include?("20") %>
            <% warehouse_idx = @warehouses_list[item_idx].index("20") %>
            <td><%= @warehouse_stock_list[item_idx][warehouse_idx] %></td>
          <% else %><td> - </td>
          <% end %>

          <% if @other_list[item_idx] != 0%>
            <td><%= @other_list[item_idx] %></td>
          <% else %><td> - </td>
          <% end %>

          <% if @total_list[item_idx] != 0%><td><%= @total_list[item_idx] %></td>
          <% else %><td> - </td>
          <% end %>

          <% if @quantity_to_be_delivered[item_idx] != 0.0 %><td><%= @quantity_to_be_delivered[item_idx] %></td>
          <% else %><td> - </td>
          <% end %>

          <% if @warehouses_list[item_idx].include?("2") %>
            <% warehouse_idx = @warehouses_list[item_idx].index("2") %>
            <td><%= @warehouse_stock_list[item_idx][warehouse_idx] %></td>
          <% else %><td> - </td>
          <% end %>
        </tr>
        <% item_idx+= 1 %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/stocks/_form.html.erb
<div class="ui grid">
  <div class="centered fifteen wide column">
<%= form_with(model: stock, class: "ui form") do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :warehouse %>
    <%= form.text_field :warehouse, placeholder: "Warehouse (Eg: 1, PROD, 2)" %>
  </div>

  <div class="field">
    <%= form.label :item_code %>
    <%= form.text_field :item_code, placeholder: "Item Code (Eg: 411002-205, 411002-BLK)" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, placeholder: "Description (Eg: 1, PROD, 2)" %>
  </div>

  <div class="field">
    <%= form.label :assortment %>
    <%= form.number_field :assortment %>
  </div>

  <div class="field">
    <%= form.label :item_group %>
    <%= form.text_field :item_group %>
  </div>

  <div class="field">
    <%= form.label :item_unit %>
    <%= form.text_field :item_unit, placeholder: "Item Unit (Eg: Kg, Litre) " %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.text_field :stock, placeholder: "Stock Amount (Eg: 100.5, 2.5)" %>
  </div>

  <div class="field">
    <%= form.label :qty_delivery %>
    <%= form.text_field :qty_delivery, placeholder: "Quantity to be delivered (Eg: 100.5, 2.5)" %>
  </div>

  <div class="actions">
      <%= form.submit "Add New Stock", class: "ui submit button"%>
  </div>
<% end %>
  </div>
</div>
<br>

app/views/stocks/_header.html.erb
<p></p>

<h1 class="ui centered header">Finished Goods Stock</h1>

<div id="navbar1" class="ui inverted menu">
  <%= link_to 'All Entries', stocks_index_path, class: current_class?(root_path)%>
  <%= link_to 'Report 1', report1_path, class: current_class?(report1_path) %>
  <%= link_to 'Report 2', root_path, class: current_class?(report2_path)%>
</div>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<div class="ui grid">
  <div class="fifteen wide column">
      <%= link_to 'New Stock',new_stock_path, class: "ui black basic right floated button"%>
  </div>
</div>

<div class="table-responsive">
    <table class="tableFixHead table-dark table-striped table-bordered table">
      <thead>
      <tr>
        <th>Warehouse</th>
        <th>Item code</th>
        <th>Description</th>
        <th>Assortment</th>
        <th>Item group</th>
        <th>Item unit</th>
        <th>Stock</th>
        <th>Quantity to be delivered</th>

      </tr>
      </thead>

      <tbody>
      <% @stocks.each do |stock| %>
        <tr>
          <td><%= stock.warehouse %></td>
          <td><%= stock.item_code %></td>
          <td><%= stock.description %></td>
          <td><%= stock.assortment %></td>
          <td><%= stock.item_group %></td>
          <td><%= stock.item_unit %></td>
          <td><%= stock.stock %></td>
          <td><%= stock.qty_delivery %></td>
          <td><%= link_to 'Show', stock %></td>
          <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
          <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
</div>

app/views/stocks/new.html.erb
<div class="ui grid">
  <div class="centered fifteen wide column">
    <h1>New Stock</h1>

    <%= render 'form', stock: @stock %>

    <%= link_to 'Back', stocks_path, class: "ui black basic button" %>

  </div>
</div>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Warehouse:</strong>
  <%= @stock.warehouse %>
</p>

<p>
  <strong>Item code:</strong>
  <%= @stock.item_code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @stock.description %>
</p>

<p>
  <strong>Assortment:</strong>
  <%= @stock.assortment %>
</p>

<p>
  <strong>Item group:</strong>
  <%= @stock.item_group %>
</p>

<p>
  <strong>Item unit:</strong>
  <%= @stock.item_unit %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @stock.stock %>
</p>

<p>
  <strong>Qty delivery:</strong>
  <%= @stock.qty_delivery %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>